package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"test/fitrang-main/analysis_service/graph/model"
)

// GetProfiles is the resolver for the getProfiles field.
func (r *queryResolver) GetProfiles(ctx context.Context) ([]*model.Profile, error) {
	panic(fmt.Errorf("not implemented: GetProfiles - getProfiles"))
}

// GetVerdict is the resolver for the getVerdict field.
func (r *queryResolver) GetVerdict(ctx context.Context, username string) (*model.Verdict, error) {
	panic(fmt.Errorf("not implemented: GetVerdict - getVerdict"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
