package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	model1 "github.com/Foxtrot-14/FitRang/analysis-service/graph/model"
)

// GetProfiles is the resolver for the getProfiles field.
func (r *queryResolver) GetProfiles(ctx context.Context) ([]*model1.Profile, error) {
	return r.Resolver.S.GetProfiles(ctx)
}

// GetVerdict is the resolver for the getVerdict field.
func (r *queryResolver) GetVerdict(ctx context.Context, input model1.VerdictInput) (*model1.Verdict, error) {
	return r.Resolver.S.GetVerdict(ctx, input)
}

// GetMyVerdict is the resolver for the getMyVerdict field.
func (r *queryResolver) GetMyVerdict(ctx context.Context, input model1.MyVerdictInput) (*model1.Verdict, error) {
	return r.Resolver.S.GetMyVerdict(ctx, input)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
