// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MyVerdictInput struct {
	Product string `json:"product"`
}

type Profile struct {
	ID         string  `json:"id"`
	FullName   string  `json:"fullName"`
	Username   string  `json:"username"`
	ProfileURL *string `json:"profileUrl,omitempty"`
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
}

type Query struct {
}

type Verdict struct {
	Analysis    string `json:"analysis"`
	Score       int32  `json:"score"`
	Suitability string `json:"suitability"`
}

type VerdictInput struct {
	Username string `json:"username"`
	Product  string `json:"product"`
}
