// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Profile struct {
	ID           string       `json:"id"`
	FullName     string       `json:"fullName"`
	Username     string       `json:"username"`
	AccessStatus AccessStatus `json:"accessStatus"`
	ProfileURL   *string      `json:"profileUrl,omitempty"`
	CreatedAt    string       `json:"createdAt"`
	UpdatedAt    string       `json:"updatedAt"`
}

type Query struct {
}

type Verdict struct {
	Analysis    string `json:"analysis"`
	Score       int32  `json:"score"`
	Suitability string `json:"suitability"`
}

type AccessStatus string

const (
	AccessStatusYes       AccessStatus = "YES"
	AccessStatusNo        AccessStatus = "NO"
	AccessStatusRequested AccessStatus = "REQUESTED"
	AccessStatusOwner     AccessStatus = "OWNER"
)

var AllAccessStatus = []AccessStatus{
	AccessStatusYes,
	AccessStatusNo,
	AccessStatusRequested,
	AccessStatusOwner,
}

func (e AccessStatus) IsValid() bool {
	switch e {
	case AccessStatusYes, AccessStatusNo, AccessStatusRequested, AccessStatusOwner:
		return true
	}
	return false
}

func (e AccessStatus) String() string {
	return string(e)
}

func (e *AccessStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccessStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccessStatus", str)
	}
	return nil
}

func (e AccessStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccessStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccessStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
